// src/app/api/chat/analyze/intent-examples-en.ts
import type { Intent } from "../intents";

export type ExampleIntent = Exclude<Intent, "profanity" | "fallback">;

export const intentExamplesEn: Array<{
  intent: ExampleIntent;
  phrases: string[];
}> = [
  {
    intent: "greeting",
    phrases: [
      "hi",
      "hello",
      "hey",
      "hey there",
      "good morning",
      "good afternoon",
      "good evening",
      "whats up",
      "sup",
      "yo",
    ],
  },
  {
    intent: "about",
    phrases: [
      "about you",
      "tell me about yourself",
      "introduce yourself",
      "who are you",
      "what do you do",
      "what is this site",
      "what can you do",
      "what can you help with",
    ],
  },
  {
    intent: "age",
    phrases: [
      "how old are you",
      "what is your age",
      "your age",
      "when were you born",
      "what year were you born",
      "whats your birth year",
    ],
  },
  {
    intent: "origin",
    phrases: [
      "where are you from",
      "where were you born",
      "where do you live",
      "where are you based",
      "where are you located",
      "what city are you in",
      "what country are you in",
      "based in",
      "location",
    ],
  },
  {
    intent: "languagesSpoken",
    phrases: [
      "what languages do you speak",
      "which languages do you speak",
      "what languages can you speak",
      "do you speak english",
      "do you speak spanish",
      "can you speak spanish",
      "can you reply in spanish",
      "can you reply in english",
    ],
  },
  {
    intent: "stack",
    phrases: [
      "tech stack",
      "your tech stack",
      "technology stack",
      "what technologies do you use",
      "what tools do you use",
      "what frameworks do you use",
      "what languages do you use",
      "what do you work with",
      "your skills",
      "what are your skills",
      "skills and tools",
      "stack",
    ],
  },
  {
    intent: "projects",
    phrases: [
      "projects",
      "your projects",
      "show me your projects",
      "what have you built",
      "what did you build",
      "what are you working on",
      "portfolio",
      "show me your portfolio",
      "things youve built",
    ],
  },
  {
    intent: "experience",
    phrases: [
      "experience",
      "work experience",
      "professional experience",
      "your background",
      "tell me about your experience",
      "what roles have you had",
      "what have you worked on",
      "employment history",
    ],
  },
  {
    intent: "contact",
    phrases: [
      "contact",
      "how can i contact you",
      "how do i contact you",
      "email",
      "your email",
      "linkedin",
      "your linkedin",
      "github",
      "your github",
      "how to reach you",
    ],
  },
  {
    intent: "cv",
    phrases: [
      "cv",
      "resume",
      "résumé",
      "your resume",
      "your cv",
      "download your cv",
      "can i see your resume",
    ],
  },
  {
    intent: "personal",
    phrases: [
      "hobbies",
      "what do you do for fun",
      "what do you like to do",
      "what do you like",
      "what games do you play",
      "music you like",
      "favorite food",
      "favourite food",
      "personal interests",
    ],
  },
  {
    intent: "availability",
    phrases: [
      "are you available",
      "are you available for work",
      "are you open to work",
      "open to work",
      "available for hire",
      "can you take new clients",
      "are you taking clients",
    ],
  },
  {
    intent: "pricing",
    phrases: [
      "pricing",
      "rates",
      "your rate",
      "hourly rate",
      "day rate",
      "how much do you charge",
      "cost",
      "quote",
    ],
  },
  {
    intent: "services",
    phrases: [
      "services",
      "what services do you offer",
      "what do you offer",
      "what can you build for me",
      "consulting",
      "freelance",
    ],
  },
  {
    intent: "education",
    phrases: [
      "education",
      "where did you study",
      "what did you study",
      "degree",
      "university",
      "college",
    ],
  },
  {
    intent: "certifications",
    phrases: [
      "certifications",
      "certificates",
      "do you have certifications",
      "aws certified",
      "google certification",
    ],
  },
  {
    intent: "blog",
    phrases: [
      "blog",
      "articles",
      "writing",
      "posts",
      "do you write",
      "have you written anything",
    ],
  },
  {
    intent: "scheduling",
    phrases: [
      "book a call",
      "schedule a call",
      "set up a meeting",
      "can we meet",
      "calendar",
      "availability for a call",
    ],
  },
  {
    intent: "timezone",
    phrases: [
      "timezone",
      "what time zone are you in",
      "your time zone",
      "working hours",
      "hours do you work",
    ],
  },
  {
    intent: "relocation",
    phrases: [
      "remote",
      "onsite",
      "hybrid",
      "are you willing to relocate",
      "can you relocate",
      "do you work remotely",
    ],
  },
  {
    intent: "opensource",
    phrases: [
      "open source",
      "oss",
      "contributions",
      "do you contribute to open source",
    ],
  },
  {
    intent: "support",
    phrases: [
      "help",
      "how does this work",
      "what can i ask",
      "commands",
      "how to use this",
    ],
  },
];
