// src/app/api/chat/analyze/intent-examples-es.ts
import type { Intent } from "../intents";

export type ExampleIntent = Exclude<Intent, "profanity" | "fallback">;

export const intentExamplesEs: Array<{
  intent: ExampleIntent;
  phrases: string[];
}> = [
  {
    intent: "greeting",
    phrases: [
      "hola",
      "buenas",
      "buen día",
      "buenos días",
      "buenas tardes",
      "buenas noches",
      "qué tal",
      "cómo va",
      "cómo estás",
      "cómo andás",
      "todo bien",
      "cómo te va",
      "qué hacés",
      "qué hay de nuevo",
      "un gusto",
      "encantado",
      "mucho gusto",
    ],
  },
  {
    intent: "about",
    phrases: [
      "sobre vos",
      "sobre ti",
      "contame sobre vos",
      "cuéntame sobre ti",
      "presentate",
      "preséntate",
      "quién eres",
      "qué haces",
      "qué podés hacer",
      "qué puedes hacer",
      "en qué me podés ayudar",
      "en qué me puedes ayudar",
      "a qué te dedicás",
      "a qué te dedicas",
      "quién sos",
      "qué sos",
      "qué sabés hacer",
      "qué sabes hacer",
      "qué funciones tenés",
      "qué funciones tienes",
      "para qué servís",
      "para qué sirves",
      "decime quién sos",
      "dime quién eres",
      "explicame qué haces",
      "explícame qué haces",
    ],
  },
  {
    intent: "age",
    phrases: [
      "cuántos años tenés",
      "cuántos años tienes",
      "qué edad tenés",
      "qué edad tienes",
      "tu edad",
      "decime tu edad",
      "dime tu edad",
      "cuándo naciste",
      "en qué año naciste",
      "año de nacimiento",
      "cuál es tu edad",
      "me decís tu edad",
      "me dices tu edad",
      "qué tan viejo sos",
      "qué tan vieja sos",
      "edad que tenés",
      "edad que tienes",
      "de qué año sos",
      "de qué año eres",
    ],
  },
  {
    intent: "origin",
    phrases: [
      "de dónde eres",
      "de dónde sos",
      "dónde naciste",
      "en dónde naciste",
      "dónde vivís",
      "dónde vives",
      "dónde estás",
      "en dónde estás",
      "en qué ciudad estás",
      "dónde estás ubicado",
      "dónde estás ubicada",
      "dónde estás radicado",
      "dónde estás radicada",
      "ubicación",
      "cuál es tu ubicación",
      "dónde te encontrás",
      "en dónde te encontrás",
      "de qué país sos",
      "de qué país eres",
      "en qué país estás",
    ],
  },
  {
    intent: "languagesSpoken",
    phrases: [
      "qué idiomas hablás",
      "qué idiomas hablas",
      "qué idiomas sabés",
      "qué idiomas sabes",
      "hablás inglés",
      "hablas inglés",
      "hablás español",
      "hablas español",
      "podés hablar español",
      "puedes hablar español",
      "podés responder en español",
      "puedes responder en español",
      "podés responder en inglés",
      "puedes responder en inglés",
      "en qué idiomas podés hablar",
      "en qué idiomas puedes hablar",
      "qué lenguajes hablás",
      "qué lenguajes hablas",
      "sabes inglés",
      "sabés inglés",
    ],
  },
  {
    intent: "stack",
    phrases: [
      "stack",
      "tecnologias",
      "stack tecnológico",
      "stack tecnologico",
      "tu stack",
      "tu stack tecnológico",
      "tu stack tecnologico",
      "tecnologías que usas",
      "tecnologias que usas",
      "qué tecnologías usas",
      "que tecnologias usas",
      "qué herramientas usas",
      "que herramientas usas",
      "qué frameworks usas",
      "que frameworks usas",
      "cuáles son tus habilidades",
      "cuales son tus habilidades",
      "tus habilidades",
      "tecnologías",
      "tecnologias",
    ],
  },
  {
    intent: "projects",
    phrases: [
      "proyectos",
      "tus proyectos",
      "muéstrame tus proyectos",
      "muestrame tus proyectos",
      "qué construiste",
      "que construiste",
      "qué has construido",
      "que has construido",
      "en qué trabajaste",
      "en que trabajaste",
      "portafolio",
      "portfolio",
      "muéstrame tu portafolio",
      "muestrame tu portafolio",
    ],
  },
  {
    intent: "experience",
    phrases: [
      "experiencia",
      "experiencia laboral",
      "experiencia profesional",
      "tu experiencia",
      "tu background",
      "tu trayectoria",
      "cuál es tu experiencia",
      "cual es tu experiencia",
      "en qué trabajaste",
      "en que trabajaste",
      "historial laboral",
    ],
  },
  {
    intent: "contact",
    phrases: [
      "contactar",
      "contacto",
      "como puedo contactarte",
      "como te contacto",
      "correo",
      "correo electrónico",
      "correo electronico",
      "tu correo",
      "tu email",
      "linkedin",
      "github",
      "cómo te encuentro",
      "como te encuentro",
    ],
  },
  {
    intent: "cv",
    phrases: [
      "currículum",
      "curriculum",
      "cv",
      "tu cv",
      "tu curriculum",
      "tu currículum",
      "hoja de vida",
      "ver tu cv",
      "descargar tu cv",
      "ver tu currículum",
      "ver tu curriculum",
    ],
  },
  {
    intent: "personal",
    phrases: [
      "hobbies",
      "pasatiempos",
      "qué haces en tu tiempo libre",
      "que haces en tu tiempo libre",
      "qué te gusta hacer",
      "que te gusta hacer",
      "qué te gusta",
      "que te gusta",
      "juegas videojuegos",
      "qué juegos juegas",
      "que juegos juegas",
      "qué música te gusta",
      "que musica te gusta",
      "comida favorita",
      "intereses personales",
    ],
  },
  {
    intent: "availability",
    phrases: [
      "estás disponible",
      "estas disponible",
      "estás disponible para trabajar",
      "estas disponible para trabajar",
      "estás buscando trabajo",
      "estas buscando trabajo",
      "estás abierto a trabajar",
      "estas abierto a trabajar",
      "disponible para contratar",
      "estás tomando clientes",
      "estas tomando clientes",
    ],
  },
  {
    intent: "pricing",
    phrases: [
      "precio",
      "precios",
      "tarifas",
      "tu tarifa",
      "tarifa por hora",
      "cuánto cobras",
      "cuanto cobras",
      "costo",
      "presupuesto",
      "cotización",
      "cotizacion",
    ],
  },
  {
    intent: "services",
    phrases: [
      "servicios",
      "qué servicios ofreces",
      "que servicios ofreces",
      "qué ofreces",
      "que ofreces",
      "consultoría",
      "consultoria",
      "freelance",
    ],
  },
  {
    intent: "education",
    phrases: [
      "educación",
      "educacion",
      "dónde estudiaste",
      "donde estudiaste",
      "qué estudiaste",
      "que estudiaste",
      "título",
      "titulo",
      "universidad",
      "facultad",
    ],
  },
  {
    intent: "certifications",
    phrases: [
      "certificaciones",
      "certificados",
      "tienes certificaciones",
      "tenes certificaciones",
    ],
  },
  {
    intent: "blog",
    phrases: [
      "blog",
      "artículos",
      "articulos",
      "escritura",
      "publicaciones",
      "escribes",
    ],
  },
  {
    intent: "scheduling",
    phrases: [
      "agendar una llamada",
      "programar una llamada",
      "podemos hablar",
      "podemos reunirnos",
      "calendario",
      "coordinar una reunión",
      "coordinar una reunion",
    ],
  },
  {
    intent: "timezone",
    phrases: [
      "zona horaria",
      "en qué zona horaria estás",
      "en que zona horaria estas",
      "tu zona horaria",
      "horario",
      "horarios",
      "horario de trabajo",
    ],
  },
  {
    intent: "relocation",
    phrases: [
      "remoto",
      "presencial",
      "híbrido",
      "hibrido",
      "te puedes mudar",
      "puedes reubicarte",
      "trabajas remoto",
      "trabajas a distancia",
    ],
  },
  {
    intent: "opensource",
    phrases: [
      "código abierto",
      "codigo abierto",
      "open source",
      "contribuciones",
      "contribuyes a open source",
    ],
  },
  {
    intent: "support",
    phrases: [
      "ayuda",
      "cómo funciona",
      "como funciona",
      "qué puedo preguntar",
      "que puedo preguntar",
      "comandos",
      "cómo usar esto",
      "como usar esto",
    ],
  },
];
